# Data Types

In [10]:
import numpy as np


In [111]:
data = [1.2345, -1, 1000000, 100000000000000.1]

In [114]:
data_as_text = ','.join([str(x) for x in data])

In [115]:
print("Bytes in text File:")
print(list(np.frombuffer(data_as_text.encode('ascii'), dtype='uint8')))
print()
print("If you opened with a text editor: ")
print(data_as_text)
print()
print("Length of file:", len(data_as_text))

Bytes in text File:
[49, 46, 50, 51, 52, 53, 44, 45, 49, 44, 49, 48, 48, 48, 48, 48, 48, 44, 49, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 46, 49]

If you opened with a text editor: 
1.2345,-1,1000000,100000000000000.1

Length of file: 35


![ASCII Table](https://upload.wikimedia.org/wikipedia/commons/d/dd/Code_Page_850_es.png)

## Signed Integers

In [125]:
data_as_int = np.array(data, dtype=np.int32)
data_as_int

array([        1,        -1,   1000000, 276447232], dtype=int32)

In [126]:
data_as_int.view(np.uint8).reshape(len(data_as_int), -1)

array([[  1,   0,   0,   0],
       [255, 255, 255, 255],
       [ 64,  66,  15,   0],
       [  0,  64, 122,  16]], dtype=uint8)

## Unsigned Integers

In [127]:
data_as_uint = np.array(data, dtype=np.uint32)
data_as_uint

array([         1, 4294967295,    1000000,  276447232], dtype=uint32)

In [128]:
data_as_uint.view(np.uint8).reshape(len(data_as_uint), -1)

array([[  1,   0,   0,   0],
       [255, 255, 255, 255],
       [ 64,  66,  15,   0],
       [  0,  64, 122,  16]], dtype=uint8)

## Small Integers

In [129]:
data_as_int16 = np.array(data, dtype=np.int16)
data_as_int16

array([    1,    -1, 16960, 16384], dtype=int16)

In [130]:
data_as_int16.view(np.uint8).reshape(len(data_as_int16), -1)

array([[  1,   0],
       [255, 255],
       [ 64,  66],
       [  0,  64]], dtype=uint8)

## floating points

In [131]:
data_as_float32 = np.array(data, dtype=np.float32)
data_as_float32

array([ 1.2345e+00, -1.0000e+00,  1.0000e+06,  1.0000e+14], dtype=float32)

In [132]:
data_as_float32.view(np.uint8).reshape(len(data_as_float32), -1)

array([[ 25,   4, 158,  63],
       [  0,   0, 128, 191],
       [  0,  36, 116,  73],
       [ 33, 230, 181,  86]], dtype=uint8)

In [155]:
large_float = np.float32(data[-1])
print(f"{large_float}")
print()

large_float2 = np.float64(data[-1])
print(f"{large_float2}")
print(f"{large_float2} * 10_000 = {large_float2 * 10_000}")
print(f"{large_float2} * 10_000_000 = {large_float2 * 10_000_000}")
print(f"{large_float2} * 10_000_000 = {large_float2 * 10_000_000}")

100000000376832.0

100000000000000.1
100000000000000.1 * 10_000 = 1.0000000000000009e+18
100000000000000.1 * 10_000_000 = 1.0000000000000009e+21
100000000000000.1 * 10_000_000_000 = 1.0000000000000009e+24


# Do not compare float with the equal symbol !!!

In [158]:
start = np.float32(0.5)
end = np.float32(1000.1)
step = np.float32(0.1)

In [160]:
print("Expected number of steps: ", (end - start)/ step)

Expected number of steps:  9996.0


In [165]:
i = start
while i != end:
    i+=step
    print(f"{i}")
    if i > 20000:
        break

0.6000000238418579
0.7000000476837158
0.8000000715255737
0.9000000953674316
1.0000001192092896
1.1000001430511475
1.2000001668930054
1.3000001907348633
1.4000002145767212
1.500000238418579
1.600000262260437
1.700000286102295
1.8000003099441528
1.9000003337860107
2.000000238418579
2.1000001430511475
2.200000047683716
2.299999952316284
2.3999998569488525
2.499999761581421
2.5999996662139893
2.6999995708465576
2.799999475479126
2.8999993801116943
2.9999992847442627
3.099999189376831
3.1999990940093994
3.2999989986419678
3.399998903274536
3.4999988079071045
3.599998712539673
3.699998617172241
3.7999985218048096
3.899998426437378
3.9999983310699463
4.099998474121094
4.199998378753662
4.2999982833862305
4.399998188018799
4.499998092651367
4.5999979972839355
4.699997901916504
4.799997806549072
4.899997711181641
4.999997615814209
5.099997520446777
5.199997425079346
5.299997329711914
5.399997234344482
5.499997138977051
5.599997043609619
5.6999969482421875
5.799996852874756
5.899996757507324
5.9

712.9729614257812
713.0729370117188
713.1729125976562
713.2728881835938
713.3728637695312
713.4728393554688
713.5728149414062
713.6727905273438
713.7727661132812
713.8727416992188
713.9727172851562
714.0726928710938
714.1726684570312
714.2726440429688
714.3726196289062
714.4725952148438
714.5725708007812
714.6725463867188
714.7725219726562
714.8724975585938
714.9724731445312
715.0724487304688
715.1724243164062
715.2723999023438
715.3723754882812
715.4723510742188
715.5723266601562
715.6723022460938
715.7722778320312
715.8722534179688
715.9722290039062
716.0722045898438
716.1721801757812
716.2721557617188
716.3721313476562
716.4721069335938
716.5720825195312
716.6720581054688
716.7720336914062
716.8720092773438
716.9719848632812
717.0719604492188
717.1719360351562
717.2719116210938
717.3718872070312
717.4718627929688
717.5718383789062
717.6718139648438
717.7717895507812
717.8717651367188
717.9717407226562
718.0717163085938
718.1716918945312
718.2716674804688
718.3716430664062
718.471618

1477.686279296875
1477.7862548828125
1477.88623046875
1477.9862060546875
1478.086181640625
1478.1861572265625
1478.2861328125
1478.3861083984375
1478.486083984375
1478.5860595703125
1478.68603515625
1478.7860107421875
1478.885986328125
1478.9859619140625
1479.0859375
1479.1859130859375
1479.285888671875
1479.3858642578125
1479.48583984375
1479.5858154296875
1479.685791015625
1479.7857666015625
1479.8857421875
1479.9857177734375
1480.085693359375
1480.1856689453125
1480.28564453125
1480.3856201171875
1480.485595703125
1480.5855712890625
1480.685546875
1480.7855224609375
1480.885498046875
1480.9854736328125
1481.08544921875
1481.1854248046875
1481.285400390625
1481.3853759765625
1481.4853515625
1481.5853271484375
1481.685302734375
1481.7852783203125
1481.88525390625
1481.9852294921875
1482.085205078125
1482.1851806640625
1482.28515625
1482.3851318359375
1482.485107421875
1482.5850830078125
1482.68505859375
1482.7850341796875
1482.885009765625
1482.9849853515625
1483.0849609375
1483.18493

2290.683837890625
2290.783935546875
2290.884033203125
2290.984130859375
2291.084228515625
2291.184326171875
2291.284423828125
2291.384521484375
2291.484619140625
2291.584716796875
2291.684814453125
2291.784912109375
2291.885009765625
2291.985107421875
2292.085205078125
2292.185302734375
2292.285400390625
2292.385498046875
2292.485595703125
2292.585693359375
2292.685791015625
2292.785888671875
2292.885986328125
2292.986083984375
2293.086181640625
2293.186279296875
2293.286376953125
2293.386474609375
2293.486572265625
2293.586669921875
2293.686767578125
2293.786865234375
2293.886962890625
2293.987060546875
2294.087158203125
2294.187255859375
2294.287353515625
2294.387451171875
2294.487548828125
2294.587646484375
2294.687744140625
2294.787841796875
2294.887939453125
2294.988037109375
2295.088134765625
2295.188232421875
2295.288330078125
2295.388427734375
2295.488525390625
2295.588623046875
2295.688720703125
2295.788818359375
2295.888916015625
2295.989013671875
2296.089111328125
2296.18920

3055.630126953125
3055.730224609375
3055.830322265625
3055.930419921875
3056.030517578125
3056.130615234375
3056.230712890625
3056.330810546875
3056.430908203125
3056.531005859375
3056.631103515625
3056.731201171875
3056.831298828125
3056.931396484375
3057.031494140625
3057.131591796875
3057.231689453125
3057.331787109375
3057.431884765625
3057.531982421875
3057.632080078125
3057.732177734375
3057.832275390625
3057.932373046875
3058.032470703125
3058.132568359375
3058.232666015625
3058.332763671875
3058.432861328125
3058.532958984375
3058.633056640625
3058.733154296875
3058.833251953125
3058.933349609375
3059.033447265625
3059.133544921875
3059.233642578125
3059.333740234375
3059.433837890625
3059.533935546875
3059.634033203125
3059.734130859375
3059.834228515625
3059.934326171875
3060.034423828125
3060.134521484375
3060.234619140625
3060.334716796875
3060.434814453125
3060.534912109375
3060.635009765625
3060.735107421875
3060.835205078125
3060.935302734375
3061.035400390625
3061.13549

3859.614501953125
3859.714599609375
3859.814697265625
3859.914794921875
3860.014892578125
3860.114990234375
3860.215087890625
3860.315185546875
3860.415283203125
3860.515380859375
3860.615478515625
3860.715576171875
3860.815673828125
3860.915771484375
3861.015869140625
3861.115966796875
3861.216064453125
3861.316162109375
3861.416259765625
3861.516357421875
3861.616455078125
3861.716552734375
3861.816650390625
3861.916748046875
3862.016845703125
3862.116943359375
3862.217041015625
3862.317138671875
3862.417236328125
3862.517333984375
3862.617431640625
3862.717529296875
3862.817626953125
3862.917724609375
3863.017822265625
3863.117919921875
3863.218017578125
3863.318115234375
3863.418212890625
3863.518310546875
3863.618408203125
3863.718505859375
3863.818603515625
3863.918701171875
3864.018798828125
3864.118896484375
3864.218994140625
3864.319091796875
3864.419189453125
3864.519287109375
3864.619384765625
3864.719482421875
3864.819580078125
3864.919677734375
3865.019775390625
3865.11987

4465.60546875
4465.70556640625
4465.8056640625
4465.90576171875
4466.005859375
4466.10595703125
4466.2060546875
4466.30615234375
4466.40625
4466.50634765625
4466.6064453125
4466.70654296875
4466.806640625
4466.90673828125
4467.0068359375
4467.10693359375
4467.20703125
4467.30712890625
4467.4072265625
4467.50732421875
4467.607421875
4467.70751953125
4467.8076171875
4467.90771484375
4468.0078125
4468.10791015625
4468.2080078125
4468.30810546875
4468.408203125
4468.50830078125
4468.6083984375
4468.70849609375
4468.80859375
4468.90869140625
4469.0087890625
4469.10888671875
4469.208984375
4469.30908203125
4469.4091796875
4469.50927734375
4469.609375
4469.70947265625
4469.8095703125
4469.90966796875
4470.009765625
4470.10986328125
4470.2099609375
4470.31005859375
4470.41015625
4470.51025390625
4470.6103515625
4470.71044921875
4470.810546875
4470.91064453125
4471.0107421875
4471.11083984375
4471.2109375
4471.31103515625
4471.4111328125
4471.51123046875
4471.611328125
4471.71142578125
4471.811

5213.134765625
5213.23486328125
5213.3349609375
5213.43505859375
5213.53515625
5213.63525390625
5213.7353515625
5213.83544921875
5213.935546875
5214.03564453125
5214.1357421875
5214.23583984375
5214.3359375
5214.43603515625
5214.5361328125
5214.63623046875
5214.736328125
5214.83642578125
5214.9365234375
5215.03662109375
5215.13671875
5215.23681640625
5215.3369140625
5215.43701171875
5215.537109375
5215.63720703125
5215.7373046875
5215.83740234375
5215.9375
5216.03759765625
5216.1376953125
5216.23779296875
5216.337890625
5216.43798828125
5216.5380859375
5216.63818359375
5216.73828125
5216.83837890625
5216.9384765625
5217.03857421875
5217.138671875
5217.23876953125
5217.3388671875
5217.43896484375
5217.5390625
5217.63916015625
5217.7392578125
5217.83935546875
5217.939453125
5218.03955078125
5218.1396484375
5218.23974609375
5218.33984375
5218.43994140625
5218.5400390625
5218.64013671875
5218.740234375
5218.84033203125
5218.9404296875
5219.04052734375
5219.140625
5219.24072265625
5219.3408

6003.20556640625
6003.3056640625
6003.40576171875
6003.505859375
6003.60595703125
6003.7060546875
6003.80615234375
6003.90625
6004.00634765625
6004.1064453125
6004.20654296875
6004.306640625
6004.40673828125
6004.5068359375
6004.60693359375
6004.70703125
6004.80712890625
6004.9072265625
6005.00732421875
6005.107421875
6005.20751953125
6005.3076171875
6005.40771484375
6005.5078125
6005.60791015625
6005.7080078125
6005.80810546875
6005.908203125
6006.00830078125
6006.1083984375
6006.20849609375
6006.30859375
6006.40869140625
6006.5087890625
6006.60888671875
6006.708984375
6006.80908203125
6006.9091796875
6007.00927734375
6007.109375
6007.20947265625
6007.3095703125
6007.40966796875
6007.509765625
6007.60986328125
6007.7099609375
6007.81005859375
6007.91015625
6008.01025390625
6008.1103515625
6008.21044921875
6008.310546875
6008.41064453125
6008.5107421875
6008.61083984375
6008.7109375
6008.81103515625
6008.9111328125
6009.01123046875
6009.111328125
6009.21142578125
6009.3115234375
6009.4

6792.17529296875
6792.275390625
6792.37548828125
6792.4755859375
6792.57568359375
6792.67578125
6792.77587890625
6792.8759765625
6792.97607421875
6793.076171875
6793.17626953125
6793.2763671875
6793.37646484375
6793.4765625
6793.57666015625
6793.6767578125
6793.77685546875
6793.876953125
6793.97705078125
6794.0771484375
6794.17724609375
6794.27734375
6794.37744140625
6794.4775390625
6794.57763671875
6794.677734375
6794.77783203125
6794.8779296875
6794.97802734375
6795.078125
6795.17822265625
6795.2783203125
6795.37841796875
6795.478515625
6795.57861328125
6795.6787109375
6795.77880859375
6795.87890625
6795.97900390625
6796.0791015625
6796.17919921875
6796.279296875
6796.37939453125
6796.4794921875
6796.57958984375
6796.6796875
6796.77978515625
6796.8798828125
6796.97998046875
6797.080078125
6797.18017578125
6797.2802734375
6797.38037109375
6797.48046875
6797.58056640625
6797.6806640625
6797.78076171875
6797.880859375
6797.98095703125
6798.0810546875
6798.18115234375
6798.28125
6798.381

7592.75634765625
7592.8564453125
7592.95654296875
7593.056640625
7593.15673828125
7593.2568359375
7593.35693359375
7593.45703125
7593.55712890625
7593.6572265625
7593.75732421875
7593.857421875
7593.95751953125
7594.0576171875
7594.15771484375
7594.2578125
7594.35791015625
7594.4580078125
7594.55810546875
7594.658203125
7594.75830078125
7594.8583984375
7594.95849609375
7595.05859375
7595.15869140625
7595.2587890625
7595.35888671875
7595.458984375
7595.55908203125
7595.6591796875
7595.75927734375
7595.859375
7595.95947265625
7596.0595703125
7596.15966796875
7596.259765625
7596.35986328125
7596.4599609375
7596.56005859375
7596.66015625
7596.76025390625
7596.8603515625
7596.96044921875
7597.060546875
7597.16064453125
7597.2607421875
7597.36083984375
7597.4609375
7597.56103515625
7597.6611328125
7597.76123046875
7597.861328125
7597.96142578125
7598.0615234375
7598.16162109375
7598.26171875
7598.36181640625
7598.4619140625
7598.56201171875
7598.662109375
7598.76220703125
7598.8623046875
759

8400.72265625
8400.822265625
8400.921875
8401.021484375
8401.12109375
8401.220703125
8401.3203125
8401.419921875
8401.51953125
8401.619140625
8401.71875
8401.818359375
8401.91796875
8402.017578125
8402.1171875
8402.216796875
8402.31640625
8402.416015625
8402.515625
8402.615234375
8402.71484375
8402.814453125
8402.9140625
8403.013671875
8403.11328125
8403.212890625
8403.3125
8403.412109375
8403.51171875
8403.611328125
8403.7109375
8403.810546875
8403.91015625
8404.009765625
8404.109375
8404.208984375
8404.30859375
8404.408203125
8404.5078125
8404.607421875
8404.70703125
8404.806640625
8404.90625
8405.005859375
8405.10546875
8405.205078125
8405.3046875
8405.404296875
8405.50390625
8405.603515625
8405.703125
8405.802734375
8405.90234375
8406.001953125
8406.1015625
8406.201171875
8406.30078125
8406.400390625
8406.5
8406.599609375
8406.69921875
8406.798828125
8406.8984375
8406.998046875
8407.09765625
8407.197265625
8407.296875
8407.396484375
8407.49609375
8407.595703125
8407.6953125
8407.79

9193.912109375
9194.01171875
9194.111328125
9194.2109375
9194.310546875
9194.41015625
9194.509765625
9194.609375
9194.708984375
9194.80859375
9194.908203125
9195.0078125
9195.107421875
9195.20703125
9195.306640625
9195.40625
9195.505859375
9195.60546875
9195.705078125
9195.8046875
9195.904296875
9196.00390625
9196.103515625
9196.203125
9196.302734375
9196.40234375
9196.501953125
9196.6015625
9196.701171875
9196.80078125
9196.900390625
9197.0
9197.099609375
9197.19921875
9197.298828125
9197.3984375
9197.498046875
9197.59765625
9197.697265625
9197.796875
9197.896484375
9197.99609375
9198.095703125
9198.1953125
9198.294921875
9198.39453125
9198.494140625
9198.59375
9198.693359375
9198.79296875
9198.892578125
9198.9921875
9199.091796875
9199.19140625
9199.291015625
9199.390625
9199.490234375
9199.58984375
9199.689453125
9199.7890625
9199.888671875
9199.98828125
9200.087890625
9200.1875
9200.287109375
9200.38671875
9200.486328125
9200.5859375
9200.685546875
9200.78515625
9200.884765625
9200

9971.5625
9971.662109375
9971.76171875
9971.861328125
9971.9609375
9972.060546875
9972.16015625
9972.259765625
9972.359375
9972.458984375
9972.55859375
9972.658203125
9972.7578125
9972.857421875
9972.95703125
9973.056640625
9973.15625
9973.255859375
9973.35546875
9973.455078125
9973.5546875
9973.654296875
9973.75390625
9973.853515625
9973.953125
9974.052734375
9974.15234375
9974.251953125
9974.3515625
9974.451171875
9974.55078125
9974.650390625
9974.75
9974.849609375
9974.94921875
9975.048828125
9975.1484375
9975.248046875
9975.34765625
9975.447265625
9975.546875
9975.646484375
9975.74609375
9975.845703125
9975.9453125
9976.044921875
9976.14453125
9976.244140625
9976.34375
9976.443359375
9976.54296875
9976.642578125
9976.7421875
9976.841796875
9976.94140625
9977.041015625
9977.140625
9977.240234375
9977.33984375
9977.439453125
9977.5390625
9977.638671875
9977.73828125
9977.837890625
9977.9375
9978.037109375
9978.13671875
9978.236328125
9978.3359375
9978.435546875
9978.53515625
9978.634